server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://${PG_DB_URL:localhost}:7878/postgres
    username: ${PG_DB_USERNAME:postgres}
    password: ${PG_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    no.norsktipping.customer: DEBUG